version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "daily", time: "09:00", timezone: "Europe/Paris" }
    labels: ["dependencies", "auto-update"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "daily", time: "09:10", timezone: "Europe/Paris" }
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "daily", time: "09:20", timezone: "Europe/Paris" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "09:30", timezone: "Europe/Paris" }
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule: { interval: "weekly", day: "monday", time: "09:40", timezone: "Europe/Paris" }