# AURA - Gitleaks configuration

[extend]
useDefault = true

[[rules]]
id = "aura-env-files"
description = "AURA environment files"
regex = '''\.env[.\w]*'''
path = '''\.env[.\w]*$'''

[[rules]]
id = "aura-api-keys"
description = "AURA API keys"
regex = '''(?i)(aura|osint)[-_]?(api|key|token|secret)[-_]?[:=]\s*['""]?([a-zA-Z0-9]{20,})['""]?'''

[[rules]]
id = "database-urls"
description = "Database connection strings"
regex = '''(?i)(database_url|db_url|postgres|mysql)[:=]\s*['""]?[a-zA-Z0-9+]+://[^\s'"]+['""]?'''

[allowlist]
description = "Allowlist for false positives"
paths = [
    '''\.env\.example$''',
    '''\.env\.template$''',
    '''docs/.*\.md$''',
    '''README\.md$'''
]