[extend]
useDefault = true

[[rules]]
id = "aura-secrets"
description = "AURA specific secrets"
regex = '''(?i)(aura[_-]?key|aura[_-]?token|aura[_-]?secret)'''
keywords = ["aura_key", "aura_token", "aura_secret"]

[[rules]]
id = "database-urls"
description = "Database connection strings"
regex = '''(postgres|mysql|mongodb)://[^\s'"]+'''

[[rules]]
id = "api-keys"
description = "API keys"
regex = '''(?i)(api[_-]?key|access[_-]?token|secret[_-]?key)\s*[:=]\s*['"][^'"]{20,}['"]'''

[allowlist]
paths = [
    "docs/examples/",
    "tests/fixtures/",
    ".gitleaks.toml"
]