title = "AURA Gitleaks Config"
[extend]
# Keep default rules and add repo-specific allowlists below

[allowlist]
description = "Repo allowlist"
paths = [
  '''^docs/''',
  '''^reports/''',
  '''^\.github/workflows/''',
]
regexes = [
  # Add known false positives (non-sensitive example tokens) here
  '''example\.com''',
  '''localhost:''',
  '''127\.0\.0\.1:''',
]