version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aura-postgres
    environment:
      POSTGRES_DB: aura_osint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aura_secure_2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: aura-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: aura-backend
    ports:
      - "4002:4002"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:aura_secure_2025@postgres:5432/aura_osint
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: