version: '3.8'

services:
  # Tor Proxy for Darknet OSINT
  tor-proxy:
    image: dperson/torproxy:latest
    container_name: aura-tor-proxy
    ports:
      - "9050:9050"  # SOCKS5 proxy
      - "9051:9051"  # Control port
    environment:
      - TOR_CONTROL_PASSWORD=aura_tor_password_2024
      - TOR_CONTROL_PORT=9051
    volumes:
      - ./tor-config:/etc/tor
      - tor-data:/var/lib/tor
    restart: unless-stopped
    networks:
      - aura-darknet
    healthcheck:
      test: ["CMD", "curl", "--socks5", "127.0.0.1:9050", "https://check.torproject.org/api/ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Tor Browser for manual investigation
  tor-browser:
    image: jlesage/firefox
    container_name: aura-tor-browser
    ports:
      - "5800:5800"  # Web interface
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - VNC_PASSWORD=aura_vnc_2024
      - FF_OPEN_URL=about:blank
    volumes:
      - tor-browser-config:/config
      - ./tor-browser-profile:/config/profile
    networks:
      - aura-darknet
    depends_on:
      - tor-proxy
    restart: unless-stopped

  # OnionScan Service
  onionscan:
    build:
      context: ./docker/onionscan
      dockerfile: Dockerfile
    container_name: aura-onionscan
    environment:
      - TOR_PROXY=tor-proxy:9050
    volumes:
      - ./data/onionscan:/data
    networks:
      - aura-darknet
    depends_on:
      - tor-proxy
    restart: unless-stopped

  # TorBot Crawler
  torbot:
    build:
      context: ./docker/torbot
      dockerfile: Dockerfile
    container_name: aura-torbot
    environment:
      - TOR_PROXY=tor-proxy:9050
      - CRAWL_DEPTH=3
      - MAX_PAGES=100
    volumes:
      - ./data/torbot:/data
      - ./logs/torbot:/logs
    networks:
      - aura-darknet
    depends_on:
      - tor-proxy
    restart: unless-stopped

  # H8Mail Breach Search
  h8mail:
    build:
      context: ./docker/h8mail
      dockerfile: Dockerfile
    container_name: aura-h8mail
    environment:
      - HIBP_API_KEY=${HIBP_API_KEY}
      - DEHASHED_API_KEY=${DEHASHED_API_KEY}
      - SNUSBASE_API_KEY=${SNUSBASE_API_KEY}
    volumes:
      - ./data/h8mail:/data
      - ./breach-databases:/breach-db:ro
    networks:
      - aura-darknet
    restart: unless-stopped

  # Blockchain Analysis Service
  blockchain-analyzer:
    build:
      context: ./docker/blockchain
      dockerfile: Dockerfile
    container_name: aura-blockchain
    environment:
      - BITCOIN_RPC_URL=${BITCOIN_RPC_URL}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - BLOCKCHAIN_INFO_API=${BLOCKCHAIN_INFO_API}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    volumes:
      - ./data/blockchain:/data
    networks:
      - aura-darknet
    restart: unless-stopped

  # Darknet Intelligence Database
  darknet-db:
    image: postgres:16-alpine
    container_name: aura-darknet-db
    environment:
      - POSTGRES_DB=darknet_intelligence
      - POSTGRES_USER=darknet_user
      - POSTGRES_PASSWORD=darknet_secure_2024
    volumes:
      - darknet-db-data:/var/lib/postgresql/data
      - ./database/darknet-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5434:5432"
    networks:
      - aura-darknet
    restart: unless-stopped

  # Redis for Darknet Cache
  darknet-redis:
    image: redis:7-alpine
    container_name: aura-darknet-redis
    command: redis-server --requirepass darknet_redis_2024
    volumes:
      - darknet-redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - aura-darknet
    restart: unless-stopped

  # Darknet Monitoring Dashboard
  darknet-dashboard:
    build:
      context: ./docker/darknet-dashboard
      dockerfile: Dockerfile
    container_name: aura-darknet-dashboard
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://darknet_user:darknet_secure_2024@darknet-db:5432/darknet_intelligence
      - REDIS_URL=redis://:darknet_redis_2024@darknet-redis:6379/0
      - TOR_PROXY=tor-proxy:9050
    volumes:
      - ./data/dashboard:/data
    networks:
      - aura-darknet
    depends_on:
      - darknet-db
      - darknet-redis
      - tor-proxy
    restart: unless-stopped

volumes:
  tor-data:
    driver: local
  tor-browser-config:
    driver: local
  darknet-db-data:
    driver: local
  darknet-redis-data:
    driver: local

networks:
  aura-darknet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16