version: "3.9"

services:
  postgres:
    image: timescale/timescaledb:pg16-latest
    container_name: aura_postgres
    environment:
      POSTGRES_USER: aura_admin
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    container_name: aura_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - redisdata:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: aura_qdrant
    profiles: ["vector"]
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrantdata:/qdrant/storage

volumes:
  pgdata:
  redisdata:
  qdrantdata: