#!/bin/bash
echo "🔧 Script de mise à jour Mailtrap"
echo "=================================="
echo ""
echo "1. Allez sur https://mailtrap.io"
echo "2. Cliquez sur 'Reset Credentials'"
echo "3. Copiez le nouveau mot de passe"
echo "4. Exécutez:"
echo ""
echo "   nano backend/.env.mailtrap"
echo ""
echo "5. Remplacez EMAIL_PASSWORD par le vrai mot de passe"
echo "6. Testez avec:"
echo ""
echo "   cd backend && node test-email.js"
echo ""
echo "✅ Le backend AURA OSINT est prêt !"