version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: aura_db
    environment:
      POSTGRES_USER: aura
      POSTGRES_PASSWORD: aura
      POSTGRES_DB: aura
    ports:
      - "5432:5432"
    volumes:
      - ../../var/db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aura -d aura"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aura_redis
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped