version: "3.9"

services:
  phoneinfoga:
    image: sundowndev/phoneinfoga:latest
    container_name: aura_phoneinfoga
    command: ["serve", "-p", "5005"]
    ports:
      - "5005:5005"
    volumes:
      - ../../../var/osint/phoneinfoga:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5005"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped