version: "3.9"
services:
  spiderfoot:
    image: spiderfoot/spiderfoot:latest
    container_name: aura_spiderfoot
    command: ["python3", "sf.py", "-l", "0.0.0.0:5001"]
    ports: ["5001:5001"]
    volumes:
      - ../../../var/osint/spiderfoot:/root/.spiderfoot
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  phoneinfoga:
    image: sundowndev/phoneinfoga:latest
    container_name: aura_phoneinfoga
    command: ["serve", "-p", "5005"]
    ports: ["5005:5005"]
    volumes:
      - ../../../var/osint/phoneinfoga:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:5005"]
      interval: 10s
      timeout: 5s
      retries: 12