name: SBOM Generation

on:
  push:
    tags:
      - 'browser-v*.*.*'
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: spdx-json
          output-file: aura-sbom.spdx.json

      - name: Generate provenance attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: aura-sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: aura-sbom
          path: aura-sbom.spdx.json

      - name: Attach SBOM to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: aura-sbom.spdx.json