name: Security Gates

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          redact: true

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: |
            MIT
            Apache-2.0
            BSD-2-Clause
            BSD-3-Clause
            ISC
            0BSD