name: Smoke Run (Backend + AI)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start backend
        run: |
          nohup node backend/mvp-server-fixed.js > backend.log 2>&1 &
          echo $! > backend.pid
      
      - name: Wait for health
        run: |
          for i in {1..30}; do
            if curl -sfS http://localhost:4010/ai/health >/dev/null; then
              echo "✅ Backend healthy"
              exit 0
            fi
            sleep 0.5
          done
          echo "❌ Backend not healthy" && exit 1
      
      - name: Warm-up AI
        env:
          HF_HOME: ~/.cache/huggingface
          HF_HUB_CACHE: ~/.cache/huggingface/hub
          AURA_EMBED_CACHE_DIR: ~/.cache/aura/embeddings
        run: |
          mkdir -p "$HF_HUB_CACHE" "$AURA_EMBED_CACHE_DIR"
          node scripts/audit/ai/warmup.js --embeddings 10 --llm 5 --dataset scripts/audit/ai/router-bench.dataset.json
      
      - name: Run AI checks
        run: |
          node scripts/audit/ai/embeddings-health.js
          node scripts/audit/ai/router-bench.js --dataset scripts/audit/ai/router-bench.dataset.json
      
      - name: Enforce SLOs (quick)
        run: |
          EMB_P50=$(jq -r '.performance.p50_latency_ms' reports/audit/AI/embeddings-cache-report.json)
          ACC=$(jq -r '.accuracy' reports/audit/AI/router-bench.json)
          BYP=$(jq -r '.bypass_detection_rate' reports/audit/AI/router-bench.json)
          echo "📊 Emb p50=${EMB_P50}ms, acc=${ACC}, bypass=${BYP}"
          [ "$(printf "%.0f" "$EMB_P50")" -le 30 ] || (echo "❌ Embeddings p50 > 30ms" && exit 1)
          awk "BEGIN { exit !(${ACC} >= 0.75) }" || (echo "❌ Accuracy < 0.75" && exit 1)
          awk "BEGIN { exit !(${BYP} >= 0.65) }" || (echo "❌ Bypass < 0.65" && exit 1)
          echo "✅ All SLOs met"
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-run-artifacts-${{ github.run_number }}
          path: |
            backend.log
            backend.pid
            reports/audit/AI/**
          retention-days: 7
      
      - name: Stop backend
        if: always()
        run: |
          if [ -f backend.pid ]; then
            kill $(cat backend.pid) || true
            sleep 1
            # Force kill if still running
            if kill -0 $(cat backend.pid) 2>/dev/null; then
              kill -9 $(cat backend.pid) || true
            fi
          fi